---
- name: Load kube-proxy ConfigMap
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: kube-proxy
    namespace: kube-system
    kubeconfig: "{{ kubeconfig_path }}"
  register: kube_proxy_cm

- name: Patch strictARP in kube-proxy ConfigMap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kube-proxy
        namespace: kube-system
      data:
        config.conf: >-
          {{
            transformed_config
          }}
  vars:
    transformed_config: >-
      {{
        kube_proxy_cm.resources[0].data['config.conf']
        | regex_replace('strictARP: .*', 'strictARP: ' ~ strict_arp | lower)
      }}
    kubeconfig: "{{ kubeconfig_path }}"
  when: kube_proxy_cm.resources[0].data['config.conf'] is defined

- name: Deploy or Remove MetalLB
  kubernetes.core.k8s:
    state: "{{ state }}"
    src: "{{ manifest_url }}"
