---
- name: Set strictARP in kube-proxy ConfigMap
  ansible.builtin.shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed "s/strictARP: {{ not strict_arp | lower }}/strictARP: {{ strict_arp | lower }}/" | \
    kubectl apply -f - -n kube-system
  become: false

- name: remove metallb
  ansible.builtin.command: 
    cmd: "kubectl delete -f {{ manifest_url }}"
  when: state == "absent"

- name: Deploy metallb
  ansible.builtin.command: kubectl apply -f "{{ manifest_url }}"
  when: state == "present"
