---

###
# Installs the metallb LoadBalancer.
# Allows us to expose a virtual IP to the host network in the same way as we would on a CSP
# https://metallb.universe.tf/concepts/
#

- name: Ensure addons folder to store metallb manifest exists
  ansible.builtin.file:
    path: "{{ manifest_dir }}"
    mode: "0755"
    owner: "{{ manifest_dir_owner }}"
    group: "{{ manifest_dir_group }}"
    state: directory
  when: download_manifest | bool

- name: Download metallb manifest for reference
  ansible.builtin.get_url:
    url: "{{ manifest_url }}"
    dest: "{{ manifest_dir }}/{{ manifest }}"
    mode: "0644"
    owner: "{{ manifest_owner }}"
    group: "{{ manifest_group }}"
  when: download_manifest | bool

- name: Include install_method tasks
  ansible.builtin.include_tasks: "{{ install_method }}.yml"
