---

###
# Installs the metallb LoadBalancer. 
# Allows us to expose a virtual IP to the host network in the same way as we would on a CSP
# https://metallb.universe.tf/concepts/
#

- name: remove metallb
  ansible.builtin.command: 
    cmd: "kubectl delete -f {{ manifest_name }}"
    chdir: "{{ manifest_download_dir }}"
  when: remove | bool

- name: Set strictARP in kube-proxy ConfigMap
  ansible.builtin.command: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed "s/strictARP: {{ not strict_arp | lower }}/strictARP: {{ strict_arp | lower }}/" | \
    kubectl apply -f - -n kube-system
  become: false

- name: Include install tasks
  ansible.builtin.include_tasks: install-{{ install_method }}.yml
  when: not remove | bool
